arrowParens: "avoid"
bracketSpacing: true
printWidth: 80
semi: false
singleQuote: true
tabWidth: 2
trailingComma: "es5"
useTabs: false

embeddedLanguageFormatting: "off"
overrides:
  - files:
      - "*.yaml"
      - "*.yml"
    options:
      singleQuote: false
  - files:
      - "*.md"
    options:
      printWidth: 100
      proseWrap: "always"
